---
title: '2019-05-29'
output: html_document
---
```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}

textbookURL()
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  es <- Qs -Qd
  return(list(
    供給量=Qs,
    需求量=Qd,
    超額供給量=es
  )
  )
}

demand_supply_fun(1,2,3,5,4)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  
  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent
  
    subSample <- transcriptDataFinal[logiChosenStudent,]
  
    sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    return(GPA)
  }else{
    message("查無此學號")
   
 }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}

```

```{r}
FizzbuzzFun <- function(fizzbuzz){
 if(fizzbuzz %% 15 ==0){
  return("fizzbuzz")
}
else if(fizzbuzz %% 5 ==0){
  return("buzz")
}
else if(fizzbuzz %% 3 ==0){
  return("fizz")
}
else{
  return(fizzbuzz)
} 
}

FizzbuzzFun(3)
FizzbuzzFun(5)
FizzbuzzFun(15)
FizzbuzzFun(4)
```


