---
title: '2019-04-03'
output: html_document
---


```{r}
x3 <-c ("小明","小花","小美")
y3 <-c ("小明","小華")

x3 %in% y3

```

```{r}
x3 <-c ("小明","小花")
y3 <-c ("小明","小華")
x3 == y3
x3 != y3
!(x3 == y3)

```

```{r}
x <- c(1,3,5)
y <- c(2,3,8)
!(x>y)
```

```{r}
install.packages("readr")
library("readr")
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
```{r}
head(currency)  #head 會顯示前6個元素值
class(currency)  #發現currency並非類別資料(factor)

currency <- as.factor(currency)
class(currency)
levels(currency)


length(levels(currency))  #length: 數向量內的元素個數
                          #這裡有幾種匯率？     

```

```{r}
currency2 <- c("日元","美元","日元")
currency2
currency2 == "日元"
sum(currency2 == "日元")

sum(currency == "日圓JPY/USD")  # “日圓JPY/USD”匯率有多少筆資料?

```

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)


y5 <- c("女","男","女")

y5=="女"
!(y5=="女")

#圈圈是要圈出"Rational operation"為真的元素(TRUE)在物件內的"位置"(第一個，第二個...)


(x5 %in% greatTaipei) & (y5=="女")  #同時來自於GreatTaipei 又是女性(交集)

y5
(y5 == "女")
which(y5=="女")   #顯示TRUE的位置

(x5 %in% greatTaipei) | (y5=="女")  #來自於GreatTaipei 或是女性
(x5 %in% greatTaipei) | (y5=="男")
xor(x5 %in% greatTaipei, y5=="女")  #兩筆資料扣掉交集的部分(注意中間用逗號))

```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
#install.packages("lubridate")
library("lubridate")
date <- ymd(date)           #將date轉換成"Date"的形式

class(date)
isAfter19800801 <- date >= ymd("1980-08-01")
class(isAfter19800801)

head(as.integer(date))
head(as.integer(ymd("1980-08-01")))

sum(as.integer(isAfter19800801))
sum(isAfter19800801)              #1980-08-01之後的資料有多少筆?


sum(currency3=="歐元USD/EUR")    #幣別為“歐元USD/EUR”的資料有多少筆? #sum會計算TRUE的項目
class(exchangeRate)

sum(as.integer(is.na(exchangeRate))==1)
#exchangeRate有多少筆NA? --> 或是sum(is.na(exchangeRate))  #sum會計算TRUE的項目

sum((as.integer(is.na(exchangeRate)==0))&(currency3=="歐元USD/EUR"))  
#排除NA後，幣別為“歐元USD/EUR”的資料有多少筆 
#-->或是sum((!(is.na(exchangeRate)))&(currency3=="歐元USD/EUR"))
```

作業


```{r}
library("readr")
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績


sum(major=='經濟學系')                              #第一題
sum(studentID=="5bdS6977b")                         #第二題
sum((studentID=="5bdS6977b")&(grade>=60))           #第三題
sum((major=="經濟學系")&(courseType=="選"))         #第四題
x<-sum((major=="經濟學系")&(courseType=="必")&(grade<60))
y<-sum((major=="經濟學系")&(courseType=="必"))
x/sum(y)                                            #第五題
```

